### PR TITLE
Added go-fuzz and crashers

### PR DESCRIPTION
**Pull request by gregory-m**
Decode function panics and hangs on some inputs.

### CODE REVIEW

**Comment by yvasiyarov** [comment]
@gregory-m unit tests failed. Can you, please, check your pull request again ?

**Comment by gregory-m** [comment]
This is propose of this tests.

I found (using go-fuz)z, some inputs that leading to crash.

I just put this strings into test.

Since I don't fixed anything tests will fail.

**Comment by yvasiyarov** [comment]
@gregory-m ok, got you. Anyway, thanks for this pull request. I will try to fix this test this weekend

**Comment by gregory-m** [comment]
Thanks.

**Comment by yvasiyarov** [comment]
@gregory-m this case is fixed. Can you, possibly, provide me with corpus which you used ?

**Comment by gregory-m** [comment]
Shure
https://wix-shareable.s3.amazonaws.com/fuzz.zip

**Comment by yvasiyarov** [comment]
@gregory-m thanks a lot!

**Pull request merged**
